# Generated by Django 4.1.3 on 2022-11-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('predict_propriety', models.BooleanField()),
            ],
        ),
    ]
