# Generated by Django 4.1.3 on 2022-12-01 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stocks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('open', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.stock')),
            ],
            options={
                'db_table': 'prices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('predict', models.DecimalField(decimal_places=2, max_digits=20)),
                ('up_down', models.CharField(max_length=10)),
                ('propriety', models.BooleanField(blank=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.stock')),
            ],
            options={
                'db_table': 'predicts',
                'managed': True,
            },
        ),
    ]
