# Generated by Django 4.1.3 on 2022-11-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('predict', models.DecimalField(decimal_places=2, max_digits=20)),
                ('up_down', models.BooleanField(choices=[(True, '上昇'), (False, '下降')])),
                ('propriety', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TestOHLC',
        ),
        migrations.AddField(
            model_name='price',
            name='security_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.stock'),
        ),
        migrations.AddField(
            model_name='predict',
            name='security_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.stock'),
        ),
    ]
