# Generated by Django 4.1.3 on 2022-11-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_predict_price_stock_delete_testohlc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='security_id',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='security_id',
            new_name='stock_id',
        ),
    ]
