# Generated by Django 4.1.3 on 2022-11-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_security_id_predict_stock_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
