# Generated by Django 4.1.3 on 2022-11-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_stock_id_predict_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='up_down',
            field=models.CharField(max_length=10),
        ),
    ]
